---
- name: Playbook to install nginx + uwsgi + web2py
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  become_user: "root"
  become_method: "sudo"
  tasks:
    - name: Update cache
      apt: update_cache=yes
    - name: Install apt packages
      apt:
       name:
         - ntp
         - python3-dev
         - python3-pip
         - nginx
         - git
         - uwsgi-plugin-python3
         - certbot
         - python3-certbot-nginx
         - neofetch
       state: present
       autoclean: yes

    - name: Install pip packages
      pip:
        name:
          - pip
          - uwsgi
        state: latest

    - name: Install web2py
      git:
        repo: 'https://github.com/web2py/web2py.git'
        dest: /srv/web2py

    


